import { LogicMapGenerator } from '~/lib/logic-map/generator'
import { LogicMapDAO } from '~/lib/db/dao/logic-map-dao'
import { getModelManager } from '~/lib/ai/manager'

/**
 * PRD 保存后自动生成 Logic Map（异步，不阻塞调用方）
 * 用于对话保存/更新时自动触发，确保逻辑覆盖率不为 0%
 */
export async function generateLogicMapForPRD(prdId: string, prdContent: string): Promise<void> {
  console.log(`[Logic Map] Starting auto-generation for PRD ${prdId}, content length: ${prdContent?.length || 0}`)

  // 空内容不生成
  if (!prdContent || !prdContent.trim()) {
    console.log(`[Logic Map] Skipped: empty content for PRD ${prdId}`)
    return
  }

  try {
    const runtimeConfig = useRuntimeConfig()
    const config = {
      anthropicApiKey: runtimeConfig.anthropicApiKey,
      openaiApiKey: runtimeConfig.openaiApiKey,
      googleApiKey: runtimeConfig.googleApiKey,
      glmApiKey: runtimeConfig.glmApiKey,
      dashscopeApiKey: runtimeConfig.dashscopeApiKey,
      baiduApiKey: runtimeConfig.baiduApiKey,
      deepseekApiKey: runtimeConfig.deepseekApiKey,
      ollamaBaseUrl: runtimeConfig.ollamaBaseUrl
    }

    const modelManager = getModelManager(config)
    const modelId = modelManager.getDefaultModelId()
    console.log(`[Logic Map] Using model: ${modelId}`)

    const generator = new LogicMapGenerator(config)
    const logicMapData = await generator.generateFromPRD(prdContent, {
      modelId,
      maxTokens: 4000
    })

    console.log(`[Logic Map] Generated ${logicMapData.nodes.length} nodes, ${logicMapData.edges.length} edges`)

    // 仅当生成了有效节点时才保存
    if (logicMapData.nodes.length > 0) {
      await LogicMapDAO.upsert(prdId, logicMapData, {
        modelId,
        generatedAt: new Date().toISOString(),
        autoGenerated: true
      })
      console.log(`[Logic Map] Successfully saved logic map for PRD ${prdId}`)
    } else {
      console.warn(`[Logic Map] No valid nodes generated for PRD ${prdId}, skipping save`)
    }
  } catch (error) {
    console.error(`[Logic Map] Failed to generate logic map for PRD ${prdId}:`, error)
    throw error
  }
}
